environment:

  matrix:

    - PYTHON: "C:\\Python37"
      ANACONDA: "C:\\Miniconda37"

    - PYTHON: "C:\\Python37-x64"
      ANACONDA: "C:\\Miniconda37-x64"

    - PYTHON: "C:\\Python36"
      ANACONDA: "C:\\Miniconda36"

    - PYTHON: "C:\\Python36-x64"
      ANACONDA: "C:\\Miniconda36-x64"

    - PYTHON: "C:\\Python35"
      ANACONDA: "C:\\Miniconda36"

    - PYTHON: "C:\\Python35-x64"
      ANACONDA: "C:\\Miniconda36-x64"

    - PYTHON: "C:\\Python27"
      ANACONDA: "C:\\Miniconda"

    - PYTHON: "C:\\Python27-x64"
      ANACONDA: "C:\\Miniconda-x64"

init:
  - "ECHO Python from %PYTHON%"
  - "ECHO Miniconda from %ANACONDA%"

install:
  # Python
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - python --version
  - python -m pip install --upgrade pip
  - python  -m pip --version
  - python -m pip install --upgrade wheel
  - python -m wheel version
  # Microsoft MPI (piggyback off of mpi4py appveyor setup scripts)
  - git clone https://github.com/mpi4py/mpi4py.git _mpi4py_
  - "powershell _mpi4py_\\conf\\ci\\appveyor\\install-msmpi.ps1"
  - "SetEnvMPI.cmd"
  - "SET PATH=%MSMPI_BIN%;%PATH%"
  - "powershell Remove-Item -Path _mpi4py_ -Recurse -Force"
  # Check versions
  - python --version
  - python -m pip --version
  # Install package
  - python -m pip install -r test_requirements.txt
  - python -m pip install codecov
  - python setup.py develop

build: off

test_script:
  - pytest -v --doctest-modules src/pybnb
  - pytest -v -s --cov=pybnb --cov=examples --cov=src/tests
  - "powershell Rename-Item -Path .coverage -NewName coverage.1"
  - python run-mpitests.py --mpirun="mpiexec -n 4" --no-build --with-coverage -v
  - "powershell Rename-Item -Path .coverage -NewName coverage.2"

on_success:
  - "powershell Rename-Item -Path coverage.1 -NewName .coverage.1"
  - "powershell Rename-Item -Path coverage.2 -NewName .coverage.2"
  - coverage combine
  - codecov -X gcov
